### PR TITLE
setup.py: Drop py3.4 and add py3.8

### PR DESCRIPTION
**Pull request by cclauss**
Describe what this patch does to fix the issue.

Link to any relevant issues or pull requests.

### CODE REVIEW

**Comment by tantale** [comment]
Ok to add Py 3.8.

But I’m not sure this library doesn’t work on 3.4. I would like to check that (if I can).

**Comment by cclauss** [comment]
https://devguide.python.org/#status-of-python-branches
https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by tantale** [comment]
Sorry but all tests passed on Python 3.4 with the following configuration:

```sh
tantale@iMac-de-Laurent ~/w/deprecated> python --version
Python 3.4.4
tantale@iMac-de-Laurent ~/w/deprecated> pip list
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Package            Version Location                           
------------------ ------- -----------------------------------
atomicwrites       1.4.0   
attrs              19.3.0  
coverage           4.5.4   
Deprecated         1.2.11  /Users/tantale/workspace/deprecated
importlib-metadata 1.1.3   
more-itertools     7.2.0   
packaging          20.3    
pathlib2           2.3.5   
pip                19.1.1  
pluggy             0.13.1  
py                 1.8.1   
pyparsing          2.4.7   
pytest             4.6.10  
pytest-cov         2.8.1   
scandir            1.10.0  
setuptools         43.0.0  
six                1.14.0  
wcwidth            0.1.9   
wheel              0.33.6  
wrapt              1.12.1  
zipp               1.2.0   
tantale@iMac-de-Laurent ~/w/deprecated> pytest
======================================== test session starts =========================================
platform darwin -- Python 3.4.4, pytest-4.6.10, py-1.8.1, pluggy-0.13.1
rootdir: /Users/tantale/workspace/deprecated, inifile: setup.cfg
plugins: cov-2.8.1
collected 156 items                                                                                  

tests/test.py ..                                                                               [  1%]
tests/test_deprecated.py .........................................                             [ 27%]
tests/test_deprecated_class.py .......                                                         [ 32%]
tests/test_deprecated_metaclass.py ....                                                        [ 34%]
tests/test_sphinx.py ......................................................................... [ 81%]
......................                                                                         [ 95%]
tests/test_sphinx_class.py ...                                                                 [ 97%]
tests/test_sphinx_metaclass.py ....                                                            [100%]

========================================== warnings summary ==========================================
tests/test_deprecated_class.py::test_simple_class_deprecation_with_args
  /Users/tantale/workspace/deprecated/tests/test_deprecated_class.py:148: DeprecationWarning: Call to deprecated class MyClass. (kwargs class)
    MyClass(5)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============================== 156 passed, 1 warnings in 0.44 seconds ===============================
```

**Comment by tantale** [comment]
Python 3.4 reached end-of-life but not Deprecated itself.

**Pull request closed without merging**
