### PR TITLE
Travis CI: Upgrade from Python 3.9-dev to 3.10-dev

### PR DESCRIPTION
**Pull request by cclauss**
Describe what this patch does to fix the issue.

Link to any relevant issues or pull requests.

### CODE REVIEW

**Comment by tantale** [comment]
Thank you Christian. And it's still the time to wish you an happy new year.
Regards.

**Comment by tantale** [comment]
Can you update the classifiers in setup.py too?

Thanks.

**Comment by tantale** [comment]
Forget it, I'll take care of it.

**Comment by cclauss** [comment]
I do not believe that we should declare compatibility with Python 3.10 before it is released.

**Comment by cclauss** [comment]
Happy New Year!!

**Comment by tantale** [comment]
You're right. The first release of Python 3.10 will be in October. I'll comment it.

**Pull request merged**
